name: CI/CD Development

on:
  push:
    branches: [ main ]
jobs:
  deployment:
    name: Deploy to development
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to development server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: ${{ secrets.PROJECT_PATH }}/sync.sh -b main -p ${{ secrets.PROJECT_PATH }}
