name: CI/CD Development

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        redis-version: [6, 7]
        mongodb-version: ['4.2', '4.4', '5.0', '6.0']

    steps:
      - uses: actions/checkout@v4

      - name: setup .env
        run: |
          echo "APP_PORT=5000" >> "$GITHUB_ENV"
          echo "BASE_URL=http://localhost:5000" >> "$GITHUB_ENV"
          echo "DB_HOST=127.0.0.1" >> "$GITHUB_ENV"
          echo "DB_PORT=27017" >> "$GITHUB_ENV"
          echo "DB_NAME=db_azmirizkifar_betest" >> "$GITHUB_ENV"
          echo "REDIS_PORT=6379" >> "$GITHUB_ENV"
          echo "REDIS_HOST=127.0.0.1" >> "$GITHUB_ENV"
          echo "REDIS_PASSWORD=password-redis" >> "$GITHUB_ENV"
          echo "JWT_EXPIRE=1d" >> "$GITHUB_ENV"
          echo "JWT_SECRET_KEY=azmirizkifar-betest" >> "$GITHUB_ENV"
          echo "JWT_VALIDATE_KEY=betest-validate-key" >> "$GITHUB_ENV"

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-db: db_azmirizkifar_betest

      - name: Start Redis
        uses: supercharge/redis-github-action@1.7.0
        with:
          redis-version: ${{ matrix.redis-version }}
          redis-port: 6379
          redis-password: 'password-redis'

      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  deployment:
    name: Deploy to server
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: ${{ secrets.PROJECT_PATH }}/sync.sh -b main -d "${{ secrets.PROJECT_PATH }}"
